version: "2"
services:
  loaner:
    image: alfredherr/loaner
    hostname: loaner
    container_name: loaner
    depends_on:
      - "lighthouse"
    command: ["bash","./wait-a-sec.sh"]
    ports:
      - "80:8080"
      - "81:8443"
      - "7777:7777"
    volumes:
      - "/demo:/demo"
      - "/usr/local/stackify:/usr/local/stackify"
    pid: "host"      
    extra_hosts:
      - "loaner:127.0.0.1"
  lighthouse:
    image: alfredherr/lighthouse:1.3
    hostname: lighthouse
    container_name: lighthouse
    ports:
      - "82:8181"
      - "4053:4053"
    volumes:
      - "/demo:/demo"
    extra_hosts:
      - "lighthouse:127.0.0.1"
